spring:
  datasource:
    url: jdbc:mysql://localhost:3306/ok?useUnicode=true&characterEncoding=utf-8&serverTimezone=UTC
    username: root
    password: 123456
#    driver-class-name: com.mysql.jdbc.Driver

  redis:
    host: 192.168.21.200
    port: 6379

    database: 0
    lettuce:
      pool:
        max-idle: 8
        max-active: 8
        min-idle: 0
    timeout: 5000

server:
  port: 8080

#mybatis:
#  type-Aliases-Package: com.lff.entity
#  mapper-Locations: classpath:com.lff.mapper/*.xml